USE [master]
GO

/****** Object:  Database [Olsera]    Script Date: 12/07/2024 08:48:33 ******/
CREATE DATABASE [Olsera]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Olsera', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Olsera.mdf' , SIZE = 1712128KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Olsera_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Olsera_log.ldf' , SIZE = 532480KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Olsera].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO


USE [Olsera]
GO

CREATE TABLE [dbo].[close_order](
	[id] [nvarchar](50) NOT NULL,
	[order_no] [nvarchar](50) NOT NULL,
	[reseller_order_id] [nvarchar](50) NULL,
	[provider_order_id] [nvarchar](50) NULL,
	[order_date] [datetime] NULL,
	[payment_due_date] [datetime] NULL,
	[forder_date] [datetime] NULL,
	[fpayment_due_date] [datetime] NULL,
	[customer_name] [nvarchar](max) NULL,
	[customer_email] [nvarchar](max) NULL,
	[shipping_to] [nvarchar](max) NULL,
	[currency_id] [nvarchar](50) NULL,
	[order_amount] [decimal](20, 2) NULL,
	[forder_amount] [decimal](20, 2) NULL,
	[total_amount] [decimal](20, 2) NULL,
	[ftotal_amount] [decimal](20, 2) NULL,
	[is_paid] [nvarchar](50) NULL,
	[payment_mode_id2] [nvarchar](50) NULL,
	[payment_type_id] [nvarchar](50) NULL,
	[payment_type_name] [nvarchar](50) NULL,
	[payment_ref] [nvarchar](max) NULL,
	[payment_from_bank] [nvarchar](max) NULL,
	[status] [nvarchar](50) NULL,
	[modified_time] [datetime] NULL,
	[status_desc] [nvarchar](max) NULL,
	[reseller_order_no] [nvarchar](50) NULL,
	[reseller_total_amount] [decimal](20, 2) NULL,
	[freseller_total_amount] [decimal](20, 2) NULL,
	[provider_order_no] [nvarchar](50) NULL,
	[provider_total_amount] [decimal](20, 2) NULL,
	[fprovider_total_amount] [decimal](20, 2) NULL,
	[customer_text] [nvarchar](max) NULL,
	[shipping_text] [nvarchar](max) NULL,
	[timestamp] [datetime] NULL,
	[outlet_name] [nvarchar](100) NULL,
UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[order_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[close_order_detail](
	[id] [bigint] NOT NULL,
	[order_no] [varchar](100) NULL,
	[store_id] [int] NULL,
	[serve_by_id] [int] NULL,
	[serve_by_name] [varchar](200) NULL,
	[sales_by_id] [int] NULL,
	[station] [varchar](200) NULL,
	[order_source] [char](100) NULL,
	[order_date] [date] NULL,
	[order_time] [time](7) NULL,
	[customer_id] [int] NULL,
	[table_no] [varchar](200) NULL,
	[total_guest] [int] NULL,
	[shipping_to] [varchar](255) NULL,
	[shipping_address] [varchar](255) NULL,
	[shipping_city_id] [int] NULL,
	[shipping_subdistrict_id] [int] NULL,
	[shipping_country_id] [int] NULL,
	[shipping_postal_code] [varchar](200) NULL,
	[shipping_phone] [varchar](200) NULL,
	[drop_ship_store_name] [varchar](255) NULL,
	[drop_ship_sender_name] [varchar](255) NULL,
	[drop_ship_contact_phone] [varchar](200) NULL,
	[notes] [text] NULL,
	[currency_id] [varchar](100) NULL,
	[exchange_rate] [decimal](18, 4) NULL,
	[order_amount] [decimal](18, 2) NULL,
	[non_tax_amount] [decimal](18, 2) NULL,
	[discount_sales_id] [int] NULL,
	[discount_voucher_id] [int] NULL,
	[discount_voucher_code] [varchar](250) NULL,
	[discount_amount] [decimal](18, 2) NULL,
	[tax_amount] [decimal](18, 2) NULL,
	[service_charge_amount] [decimal](18, 2) NULL,
	[shipping_cost] [decimal](18, 2) NULL,
	[redeemed_amount] [decimal](18, 2) NULL,
	[rounded_amount] [decimal](18, 2) NULL,
	[credit_payment_amount] [decimal](18, 2) NULL,
	[total_amount] [decimal](18, 2) NULL,
	[total_weight] [decimal](18, 2) NULL,
	[is_paid] [nvarchar](50) NULL,
	[cash_payment] [nvarchar](50) NULL,
	[payment_date] [datetime] NULL,
	[payment_due_date] [date] NULL,
	[payment_terms] [int] NULL,
	[payment_mode_id] [int] NULL,
	[payment_currency_id] [varchar](10) NULL,
	[payment_exchange_rate] [decimal](18, 4) NULL,
	[payment_amount] [decimal](18, 2) NULL,
	[payment_ref] [varchar](100) NULL,
	[payment_from_bank] [varchar](200) NULL,
	[payment_payee] [varchar](200) NULL,
	[payment_received_by] [varchar](200) NULL,
	[payment_mode_id2] [int] NULL,
	[payment_ref2] [varchar](100) NULL,
	[payment_amount2] [decimal](18, 2) NULL,
	[payment_charge] [decimal](18, 2) NULL,
	[shipping_courier_id] [int] NULL,
	[shipping_service_type] [varchar](100) NULL,
	[shipping_track_no] [varchar](200) NULL,
	[shipping_date] [date] NULL,
	[received_date] [date] NULL,
	[is_hold_stock] [nvarchar](50) NULL,
	[stock_deducted] [nvarchar](50) NULL,
	[total_cost_amount] [decimal](18, 2) NULL,
	[beginning_points] [int] NULL,
	[earned_points] [int] NULL,
	[redeemed_points] [int] NULL,
	[balance_points] [int] NULL,
	[auto_cancel_date] [date] NULL,
	[reseller_order_id] [bigint] NULL,
	[provider_order_id] [bigint] NULL,
	[is_posted_to_provider] [nvarchar](50) NULL,
	[cancel_by_reseller] [nvarchar](50) NULL,
	[unique_payment_code] [varchar](100) NULL,
	[jurnal_posted] [nvarchar](50) NULL,
	[status] [varchar](50) NULL,
	[stock_in_processing] [nvarchar](50) NULL,
	[stock_last_processed] [datetime] NULL,
	[created_from] [varchar](100) NULL,
	[created_by] [varchar](200) NULL,
	[created_time] [datetime] NULL,
	[modified_from] [varchar](100) NULL,
	[modified_by] [varchar](200) NULL,
	[modified_time] [datetime] NULL,
	[sales_by_name] [varchar](200) NULL,
	[currency_name] [varchar](100) NULL,
	[customer_name] [varchar](200) NULL,
	[customer_email] [varchar](200) NULL,
	[customer_phone] [varchar](100) NULL,
	[shipping_city_name] [varchar](200) NULL,
	[shipping_city_district] [varchar](200) NULL,
	[shipping_subdistrict_name] [varchar](200) NULL,
	[shipping_state_id] [int] NULL,
	[shipping_state_name] [varchar](200) NULL,
	[shipping_country_name] [varchar](200) NULL,
	[payment_type_id] [varchar](100) NULL,
	[payment_type_name] [varchar](200) NULL,
	[payment_mode_name] [varchar](200) NULL,
	[bt_bank_name] [varchar](200) NULL,
	[bt_account_name] [varchar](200) NULL,
	[bt_account_no] [varchar](100) NULL,
	[payment_instructions] [text] NULL,
	[payment_type_id2] [varchar](100) NULL,
	[payment_type_name2] [varchar](200) NULL,
	[payment_mode_name2] [varchar](200) NULL,
	[bt_bank_name2] [varchar](200) NULL,
	[bt_account_name2] [varchar](200) NULL,
	[bt_account_no2] [varchar](100) NULL,
	[payment_instructions2] [text] NULL,
	[shipping_courier_name] [varchar](200) NULL,
	[shipping_track_url] [varchar](255) NULL,
	[status_desc] [varchar](255) NULL,
	[reseller_order_no1] [varchar](10) NULL,
	[is_order_from_reseller] [nvarchar](50) NULL,
	[forder_date] [date] NULL,
	[fpayment_date] [date] NULL,
	[fpayment_due_date] [date] NULL,
	[fshipping_date] [date] NULL,
	[freceived_date] [date] NULL,
	[has_discount] [nvarchar](50) NULL,
	[has_tax] [nvarchar](50) NULL,
	[has_service_charge] [nvarchar](50) NULL,
	[has_shipping_cost] [nvarchar](50) NULL,
	[has_redeemed_amount] [nvarchar](50) NULL,
	[has_rounded_amount] [nvarchar](50) NULL,
	[forder_amount] [decimal](18, 2) NULL,
	[fdiscount_amount] [decimal](18, 2) NULL,
	[fredeemed_amount] [decimal](18, 2) NULL,
	[fshipping_cost] [decimal](18, 2) NULL,
	[ftax_amount] [decimal](18, 2) NULL,
	[fservice_charge_amount] [decimal](18, 2) NULL,
	[frounded_amount] [decimal](18, 2) NULL,
	[ftotal_amount] [decimal](18, 2) NULL,
	[fpayment_amount] [decimal](18, 2) NULL,
	[fpayment_amount2] [decimal](18, 2) NULL,
	[fcredit_payment_amount] [decimal](18, 2) NULL,
	[fpayment_charge] [decimal](18, 2) NULL,
	[attachment] [text] NULL,
	[ftotal_weight] [decimal](18, 2) NULL,
	[serve_bys] [text] NULL,
	[orderitems] [text] NULL,
	[fdiscount_percent] [decimal](5, 2) NULL,
	[total_item_qty] [int] NULL,
	[ftotal_item_qty] [int] NULL,
	[credit_outstanding_amount] [decimal](18, 2) NULL,
	[fcredit_outstanding_amount] [decimal](18, 2) NULL,
	[creditpayments] [text] NULL,
	[is_supervisor] [nvarchar](50) NULL,
	[translogs] [text] NULL,
	[self_pickup] [nvarchar](50) NULL,
	[is_credit] [nvarchar](50) NULL,
	[timestamp] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[close_order_detail_orderitem](
	[id] [nvarchar](255) NOT NULL,
	[addon_price] [decimal](18, 2) NULL,
	[amount] [decimal](18, 2) NULL,
	[cost_amount] [decimal](18, 2) NULL,
	[cost_price] [decimal](18, 2) NULL,
	[created_by] [nvarchar](255) NULL,
	[created_from] [nvarchar](255) NULL,
	[created_time] [datetime] NULL,
	[deal_id] [nvarchar](255) NULL,
	[deal_photo] [nvarchar](1000) NULL,
	[deal_photo_md] [nvarchar](1000) NULL,
	[deal_photo_xs] [nvarchar](1000) NULL,
	[deal_title] [nvarchar](1000) NULL,
	[discount] [decimal](18, 2) NULL,
	[famount] [decimal](18, 2) NULL,
	[fdiscount] [nvarchar](1000) NULL,
	[fprice] [decimal](18, 2) NULL,
	[ftotal_weight] [decimal](18, 2) NULL,
	[fweight] [decimal](18, 2) NULL,
	[loyalty_points] [decimal](18, 2) NULL,
	[modified_by] [nvarchar](255) NULL,
	[modified_from] [nvarchar](255) NULL,
	[modified_time] [datetime] NULL,
	[note] [nvarchar](max) NULL,
	[order_with_serial] [bit] NULL,
	[photo_md] [nvarchar](1000) NULL,
	[photo_variant_md] [nvarchar](1000) NULL,
	[photo_variant_xs] [nvarchar](1000) NULL,
	[photo_xs] [nvarchar](1000) NULL,
	[price] [decimal](18, 2) NULL,
	[product_combo_id] [nvarchar](255) NULL,
	[product_combo_name] [nvarchar](1000) NULL,
	[product_combo_photo] [nvarchar](1000) NULL,
	[product_combo_photo_md] [nvarchar](1000) NULL,
	[product_combo_photo_xs] [nvarchar](1000) NULL,
	[product_id] [nvarchar](1000) NULL,
	[product_name] [nvarchar](1000) NULL,
	[product_photo] [nvarchar](1000) NULL,
	[product_sku] [nvarchar](255) NULL,
	[product_variant_id] [nvarchar](255) NULL,
	[product_variant_name] [nvarchar](1000) NULL,
	[product_variant_photo] [nvarchar](1000) NULL,
	[product_variant_sku] [nvarchar](255) NULL,
	[products] [nvarchar](max) NULL,
	[qty] [int] NULL,
	[sales_order_id] [nvarchar](1000) NULL,
	[serial_no] [nvarchar](255) NULL,
	[status] [char](1) NULL,
	[total_loyalty_points] [decimal](18, 2) NULL,
	[total_weight] [nvarchar](255) NULL,
	[weight] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[products](
	[id] [int] NULL,
	[photo_md] [nvarchar](255) NULL,
	[photo_xs] [nvarchar](255) NULL,
	[name] [nvarchar](255) NULL,
	[sku] [nvarchar](50) NULL,
	[klasifikasi_id] [int] NULL,
	[klasifikasi] [nvarchar](100) NULL,
	[category_id] [int] NULL,
	[category_name] [nvarchar](100) NULL,
	[brand_id] [int] NULL,
	[brand_name] [nvarchar](100) NULL,
	[published] [nvarchar](100) NULL,
	[pos_hidden] [nvarchar](100) NULL,
	[description] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[published_date] [date] NULL,
	[collections] [nvarchar](max) NULL,
	[stock_qty] [decimal](18, 2) NULL,
	[hold_qty] [decimal](18, 2) NULL,
	[is_out_stock] [nvarchar](100) NULL,
	[low_stock_alert] [decimal](18, 2) NULL,
	[market_price] [decimal](18, 2) NULL,
	[buy_price] [decimal](18, 2) NULL,
	[fbuy_price] [nvarchar](50) NULL,
	[last_buy_price] [decimal](18, 2) NULL,
	[flast_buy_price] [nvarchar](50) NULL,
	[sell_price] [decimal](18, 2) NULL,
	[sell_price_pos] [decimal](18, 2) NULL,
	[fsell_price] [nvarchar](50) NULL,
	[fsell_price_pos] [nvarchar](50) NULL,
	[has_variant] [nvarchar](100) NULL,
	[with_lpoint] [nvarchar](100) NULL,
	[variants] [nvarchar](max) NULL,
	[store_name] [nvarchar](255) NULL,
	[store_url] [nvarchar](255) NULL,
	[track_inventory] [nvarchar](100) NULL,
	[max_sell_price] [decimal](18, 2) NULL,
	[min_sell_price] [decimal](18, 2) NULL,
	[max_sell_price_pos] [decimal](18, 2) NULL,
	[min_sell_price_pos] [decimal](18, 2) NULL,
	[fmax_sell_price] [nvarchar](50) NULL,
	[fmin_sell_price] [nvarchar](50) NULL,
	[fmax_sell_price_pos] [nvarchar](50) NULL,
	[fmin_sell_price_pos] [nvarchar](50) NULL,
	[name_sku_variant] [nvarchar](50) NULL,
	[length_dimension] [decimal](18, 2) NULL,
	[width_dimension] [decimal](18, 2) NULL,
	[high_dimension] [decimal](18, 2) NULL,
	[weight_dimension] [decimal](18, 2) NULL,
	[timestamp] [datetime] NULL,
	[outlet_name] [nvarchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE TABLE [dbo].[products_combo](
	[id] [int] NULL,
	[store_id] [int] NULL,
	[name] [nvarchar](255) NULL,
	[sku] [nvarchar](255) NULL,
	[description] [nvarchar](255) NULL,
	[buy_price] [decimal](18, 2) NULL,
	[fbuy_price] [nvarchar](255) NULL,
	[sell_price] [decimal](18, 2) NULL,
	[sell_price_pos] [decimal](18, 2) NULL,
	[fsell_price] [nvarchar](255) NULL,
	[fsell_price_pos] [nvarchar](255) NULL,
	[market_price] [decimal](18, 2) NULL,
	[fmarket_price] [nvarchar](255) NULL,
	[comission] [decimal](18, 2) NULL,
	[fcomission] [nvarchar](255) NULL,
	[loyalty_points] [decimal](18, 2) NULL,
	[require_shipping] [nvarchar](100) NULL,
	[weight] [decimal](18, 4) NULL,
	[min_order] [int] NULL,
	[max_order] [int] NULL,
	[non_taxable] [nvarchar](100) NULL,
	[track_inventory] [nvarchar](100) NULL,
	[stock_qty] [nvarchar](255) NULL,
	[low_stock_alert] [nvarchar](255) NULL,
	[accept_preorder] [nvarchar](100) NULL,
	[is_out_stock] [nvarchar](100) NULL,
	[published] [nvarchar](100) NULL,
	[published_date] [date] NULL,
	[fpublished_date] [nvarchar](255) NULL,
	[pos_sell_price_dynamic] [nvarchar](100) NULL,
	[pos_hidden] [nvarchar](100) NULL,
	[meta_keywords] [nvarchar](255) NULL,
	[meta_description] [nvarchar](255) NULL,
	[photo] [nvarchar](255) NULL,
	[photo_md] [nvarchar](255) NULL,
	[photo_xs] [nvarchar](255) NULL,
	[photo_width] [int] NULL,
	[photo_height] [int] NULL,
	[reviewer_rating] [decimal](18, 4) NULL,
	[reviewer_total] [int] NULL,
	[viewed] [int] NULL,
	[viewed_time] [datetime] NULL,
	[copy_product_combo_id] [int] NULL,
	[status] [nvarchar](100) NULL,
	[timestamp] [datetime] NULL,
	[outlet_name] [nvarchar](100) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[products_combo_detail](
	[id] [int] NULL,
	[store_id] [int] NULL,
	[name] [nvarchar](255) NULL,
	[sku] [nvarchar](255) NULL,
	[description] [nvarchar](255) NULL,
	[buy_price] [decimal](18, 2) NULL,
	[fbuy_price] [nvarchar](255) NULL,
	[sell_price] [decimal](18, 2) NULL,
	[sell_price_pos] [decimal](18, 2) NULL,
	[fsell_price] [nvarchar](255) NULL,
	[fsell_price_pos] [nvarchar](255) NULL,
	[market_price] [decimal](18, 2) NULL,
	[fmarket_price] [nvarchar](255) NULL,
	[comission] [decimal](18, 2) NULL,
	[fcomission] [nvarchar](255) NULL,
	[loyalty_points] [decimal](18, 2) NULL,
	[require_shipping] [nvarchar](100) NULL,
	[weight] [decimal](18, 4) NULL,
	[min_order] [int] NULL,
	[max_order] [int] NULL,
	[non_taxable] [nvarchar](100) NULL,
	[track_inventory] [nvarchar](100) NULL,
	[stock_qty] [nvarchar](255) NULL,
	[low_stock_alert] [nvarchar](255) NULL,
	[accept_preorder] [nvarchar](100) NULL,
	[is_out_stock] [nvarchar](100) NULL,
	[published] [nvarchar](100) NULL,
	[published_date] [date] NULL,
	[fpublished_date] [nvarchar](255) NULL,
	[pos_sell_price_dynamic] [nvarchar](100) NULL,
	[pos_hidden] [nvarchar](100) NULL,
	[meta_keywords] [nvarchar](255) NULL,
	[meta_description] [nvarchar](255) NULL,
	[photo] [nvarchar](255) NULL,
	[photo_md] [nvarchar](255) NULL,
	[photo_xs] [nvarchar](255) NULL,
	[photo_width] [int] NULL,
	[photo_height] [int] NULL,
	[reviewer_rating] [decimal](18, 4) NULL,
	[reviewer_total] [int] NULL,
	[viewed] [int] NULL,
	[viewed_time] [datetime] NULL,
	[copy_product_combo_id] [int] NULL,
	[status] [nvarchar](100) NULL,
	[items] [nvarchar](max) NULL,
	[timestamp] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[products_combo_detail_items](
	[id] [int] NULL,
	[parent_id] [int] NULL,
	[product_combo_id] [int] NULL,
	[product_id] [int] NULL,
	[product_variant_id] [int] NULL,
	[qty] [int] NULL,
	[view_order] [int] NULL,
	[photo_md] [nvarchar](255) NULL,
	[photo_xs] [nvarchar](255) NULL,
	[product_name] [nvarchar](255) NULL,
	[product_sku] [nvarchar](255) NULL,
	[product_group_name] [nvarchar](255) NULL,
	[product_variant_name] [nvarchar](255) NULL,
	[product_variant_sku] [nvarchar](255) NULL,
	[product_has_variant] [nvarchar](100) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[products_detail](
	[id] [int] NULL,
	[photo_md] [nvarchar](255) NULL,
	[photo_xs] [nvarchar](255) NULL,
	[name] [nvarchar](255) NULL,
	[sku] [nvarchar](50) NULL,
	[klasifikasi_id] [int] NULL,
	[klasifikasi] [nvarchar](100) NULL,
	[category_id] [int] NULL,
	[category_name] [nvarchar](100) NULL,
	[published_date] [date] NULL,
	[fpublished_date] [nvarchar](50) NULL,
	[stock_qty] [decimal](18, 2) NULL,
	[has_variant] [nvarchar](100) NULL,
	[with_lpoint] [nvarchar](100) NULL,
	[variant] [nvarchar](max) NULL,
	[photos] [nvarchar](max) NULL,
	[collections] [nvarchar](max) NULL,
	[store_id] [int] NULL,
	[store_name] [nvarchar](255) NULL,
	[product_group_id] [int] NULL,
	[description] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[market_price] [decimal](18, 2) NULL,
	[fmarket_price] [nvarchar](50) NULL,
	[buy_price] [decimal](18, 2) NULL,
	[last_buy_price] [decimal](18, 2) NULL,
	[sell_price] [decimal](18, 2) NULL,
	[sell_price_pos] [decimal](18, 2) NULL,
	[fbuy_price] [nvarchar](50) NULL,
	[flast_buy_price] [nvarchar](50) NULL,
	[fsell_price] [nvarchar](50) NULL,
	[fsell_price_pos] [nvarchar](50) NULL,
	[comission] [decimal](18, 2) NULL,
	[fcomission] [nvarchar](50) NULL,
	[is_comission_percentage] [nvarchar](100) NULL,
	[loyalty_points] [decimal](18, 2) NULL,
	[condition_id] [nvarchar](50) NULL,
	[brand_id] [int] NULL,
	[is_featured] [nvarchar](100) NULL,
	[is_sale] [nvarchar](100) NULL,
	[is_new_release] [nvarchar](100) NULL,
	[is_popular] [nvarchar](100) NULL,
	[is_preorder] [nvarchar](100) NULL,
	[is_out_stock] [nvarchar](100) NULL,
	[is_raw_material] [nvarchar](100) NULL,
	[track_inventory] [nvarchar](100) NULL,
	[variant_label] [nvarchar](255) NULL,
	[default_variant_id] [int] NULL,
	[require_shipping] [nvarchar](100) NULL,
	[non_taxable] [nvarchar](100) NULL,
	[weight] [decimal](18, 4) NULL,
	[fweight] [nvarchar](50) NULL,
	[min_order] [decimal](18, 2) NULL,
	[max_order] [decimal](18, 2) NULL,
	[hold_qty] [decimal](18, 2) NULL,
	[low_stock_alert] [decimal](18, 2) NULL,
	[photo_id] [int] NULL,
	[published] [nvarchar](100) NULL,
	[pos_sell_price_dynamic] [nvarchar](100) NULL,
	[pos_hidden] [nvarchar](100) NULL,
	[copy_product_id] [int] NULL,
	[predefined_order_notes] [nvarchar](max) NULL,
	[order_with_serial] [nvarchar](100) NULL,
	[has_material] [nvarchar](100) NULL,
	[supplier_id] [int] NULL,
	[status] [nvarchar](10) NULL,
	[meta_keywords] [nvarchar](max) NULL,
	[meta_description] [nvarchar](max) NULL,
	[reviewer_rating] [decimal](18, 2) NULL,
	[reviewer_total] [int] NULL,
	[viewed] [int] NULL,
	[viewed_time] [datetime] NULL,
	[created_from] [nvarchar](50) NULL,
	[created_by] [nvarchar](100) NULL,
	[created_time] [datetime] NULL,
	[modified_from] [nvarchar](50) NULL,
	[modified_by] [nvarchar](100) NULL,
	[modified_time] [datetime] NULL,
	[modified_sync_time] [datetime] NULL,
	[stock_sync_time] [datetime] NULL,
	[condition_name] [nvarchar](100) NULL,
	[brand_name] [nvarchar](100) NULL,
	[uom] [nvarchar](50) NULL,
	[max_sell_price] [decimal](18, 2) NULL,
	[min_sell_price] [decimal](18, 2) NULL,
	[max_sell_price_pos] [decimal](18, 2) NULL,
	[min_sell_price_pos] [decimal](18, 2) NULL,
	[fmax_sell_price] [nvarchar](50) NULL,
	[fmin_sell_price] [nvarchar](50) NULL,
	[fmax_sell_price_pos] [nvarchar](50) NULL,
	[fmin_sell_price_pos] [nvarchar](50) NULL,
	[has_branches_stock_info] [nvarchar](100) NULL,
	[branches_stock_info] [nvarchar](max) NULL,
	[length_dimension] [decimal](18, 2) NULL,
	[width_dimension] [decimal](18, 2) NULL,
	[high_dimension] [decimal](18, 2) NULL,
	[weight_dimension] [decimal](18, 2) NULL,
	[timestamp] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


